packages:
  - apps/*
  - packages/*/*

catalog:
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/react': ^19.2.3
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.0
  jsdom: ^27.1.0
  react: ^19.2.0
  react-dom: ^19.2.0
  turbo: ^2.6.1
  typescript: ^5.9.3
  vite: ^7.2.2
  vitest: ^4.0.8

onlyBuiltDependencies:
  - esbuild
