packages:
  - apps/*
  - packages/*/*

catalog:
  '@types/react': ^19.2.3
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.0
  react: ^19.2.0
  react-dom: ^19.2.0
  turbo: ^2.6.1
  typescript: ^5.9.3
  vite: ^7.2.2

onlyBuiltDependencies:
  - esbuild
